version: '3.4'

services:
  findpets_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_findpets_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  findpets_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_findpets_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  findpets_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_findpets_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq

  findpets_api:
    ports:
      - "10000:80"
    networks:
      - shared_findpets_net
    env_file:
      - env.api

networks:
  shared_findpets_net:
    name: find_pets
    driver: bridge